### ISSUE TITLE
Error dans le readme !

### ISSUE THREAD

**Issue by Rapiiidooo** [Chadys/Kamisado#9]
:-1:  Mentionned : "cmake CMakeList.txt" 

Or the real text to notice is :

"cmake CMakeLists.txt"

**Comment by YetiYetYet** [comment]
Omg that so unprofessionnal Chadys. I hope you will have aids

**Comment by Chadys** [comment]
YetiYetYet you're a nuisance :p Thanks Rapido, resolved
